{% set name = "JCC" %}
{% set version = "3.7" %}
{% set sha256 = "c5dd41c2b72733d2573af9f3cb982bcbadd419323fd743e96e4f1e6d3257d6eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/60/4b/ca6f79930cefc71ed39fbe792aedc129ff652570273fe042a35812a40501/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # skip: True  # [win]  Right now the conda-build is not detecting the prefix for windows https://github.com/conda/conda-build/issues/3909 Works in conda-buld 3.18.11
  number: 1

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    - jcc/config.py

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - pip
    - setuptools
    - openjdk #8.0.152  # Force anaconda openjdk

  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - pip
    - setuptools
    - openjdk #8.0.152  # Force anaconda openjdk

  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - openjdk #8.0.152  # Force anaconda openjdk

test:
  imports:
    - jcc

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  files:
    - test/*.py
    - test/java-example/*.bat
    - test/java-example/*.sh
    - test/java-example/*.java
    - test/java-example/*.py
    - test/java-example-test-parameters/*.bat
    - test/java-example-test-parameters/*.sh
    - test/java-example-test-parameters/org/jcc/test/*.java
    - test/java-example-test-parameters/*.py

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface  (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
