{% set name = "JCC" %}
{% set version = "3.6" %}
{% set sha256 = "375f25b7186a67327ba9c031ee357b85c17d1569f4c2dd1d2fccea39eb670048" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/3f/6f/123875ea113fefd766a01136fecfcb0da8b841e0cac6882ee592a14f6f2c/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    - _-_fixed_bug_with_wrongly_assuming_1BYTE_KIND_python_unicode_strings_to_be_utf-8_.patch
    - made_the_1BYTE_KIND_-__jchar_case_a_bit_faster.patch
    - added_setting_of_type___module___for_all_generated_wrapper_types_(python_3)_.patch
    - Added___module___to_JArray()_types__.patch
    - added_support_for_Python_3_8_.patch

build:
  number: 4

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    - jcc/config.py

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - openjdk 8.0.152  # Force anaconda openjdk
    - vs2015_runtime [win]

  run:
    - python
    - openjdk 8.0.152  # Force anaconda openjdk
    - vs2015_runtime [win]

test:
  imports:
    - jcc

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  files:
    - test/*.py
    - test/java-example/*.bat
    - test/java-example/*.sh
    - test/java-example/*.java
    - test/java-example/*.py
    - test/java-example-test-parameters/*.bat
    - test/java-example-test-parameters/*.sh
    - test/java-example-test-parameters/org/jcc/test/*.java
    - test/java-example-test-parameters/*.py

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
