{% set name = "JCC" %}
{% set version = "3.14" %}
{% set sha256 = "1610b99ed2f6d4d553abdbbe1e6c1f4b75ba95fc654e1776426a54bf3d756156" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/0e/4f/64976854f2809efe71335476f275ad0832fbfd3e42eff605672b18922cef/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
   - jcc_python.patch

build:
  number: 1

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    - jcc/config.py

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - openjdk 8.*
    - pip
    - build

  host:
    - python
    - setuptools
    - openjdk 8.*
    - pip
    - build

  run:
    - python
    - setuptools
    - openjdk 8.*
    - build
    - pip

test:
  imports:
    - jcc  # [not win]

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  files:
    - test/*.py
    - test/java-example/*.bat
    - test/java-example/*.sh
    - test/java-example/*.java
    - test/java-example/*.py
    - test/java-example-test-parameters/*.bat
    - test/java-example-test-parameters/*.sh
    - test/java-example-test-parameters/org/jcc/test/*.java
    - test/java-example-test-parameters/*.py
    - test/java-example-shared/*.bat
    - test/java-example-shared/*.sh
    - test/java-example-shared/*.java
    - test/java-example-shared/*.py

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface  (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
