{% set name = "JCC" %}
{% set version = "3.5" %}
{% set sha256 = "219f4ce8e0035598e43f0e9d24d3fc8ce0d27fa94b66dfa019f437cc0b19840e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/ae/b0/776a0ffd47afa9e9de8fcad15d4836577f970997799a8a242dca168508da/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

  patches:
   - pylucene-47-3.patch  # Temporary patch to better manage PYLUCENE-47 Issue

build:
  number: 1

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    # - {{SP_DIR}}/jcc/config.py
    - jcc/config.py

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - openjdk 8.0.152  # Force anaconda openjdk

  run:
    - python
    - openjdk 8.0.152  # Force anaconda openjdk

test:
  imports:
    - jcc

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  files:
    - test/*.py
    - test/java-example/*.bat
    - test/java-example/*.sh
    - test/java-example/*.java
    - test/java-example/*.py
    - test/java-example-test-parameters/*.bat
    - test/java-example-test-parameters/*.sh
    - test/java-example-test-parameters/*.java
    - test/java-example-test-parameters/*.py


about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
