{% set name = "jcc" %}
{% set version = "3.1.dev1" %}
{% set sha256 = "653e4c3b33d44dcf5ee5dbff7a5056e5d13f2cb717eb8d509d40e784b9c4eb7a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/petrushy/jcc_svn_import/raw/master/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  skip: true  # [win32 or linux32]

  number: 1

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    - {{SP_DIR}}/jcc/config.py  # [linux or osx]

  # The JCC for windows package does not have the right compile parameters for wrapping and needs these to be set
  # explicitly


requirements:
  build:
    - python
    - setuptools
    - toolchain
    - openjdk 8.0.121 1  # Force anaconda openjdk

  run:
    - python
    - openjdk 8.0.121 1  # Force anaconda openjdk


test:
  # Some package might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - jcc

  files:
    - test/myrun_test.py

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
