{% set name = "JCC" %}
{% set version = "3.11" %}
{% set sha256 = "b6fd1e2919d982845f1a8a37d213f13bcab87b393347b618bf4cb31a7d994739" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/aa/4d/09c5d09e844b2ec8b176486ade1390fa3329b938a8ec425a395fd1ea0a88/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - add_dll_win.patch

build:
  number: 2

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    - jcc/config.py

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openjdk 8
    - pip

  host:
    - python
    - setuptools
    - openjdk 8
    - pip

  run:
    - python
    - openjdk 8

test:
  imports:
    - jcc

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  files:
    - test/*.py
    - test/java-example/*.bat
    - test/java-example/*.sh
    - test/java-example/*.java
    - test/java-example/*.py
    - test/java-example-test-parameters/*.bat
    - test/java-example-test-parameters/*.sh
    - test/java-example-test-parameters/org/jcc/test/*.java
    - test/java-example-test-parameters/*.py

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface  (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
