{% set name = "JCC" %}
{% set version = "3.4" %}
{% set sha256 = "6c7922a03f699b7fe7630938f03b7ee6eec72b6f901db047093a3180db9a0f0d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/29/f5/8660a7cd624a0c5a8c10aa6917992e00e79b387b7108e1de83101b74674a/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    # - {{SP_DIR}}/jcc/config.py
    - jcc/config.py

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - openjdk 8.0.152  # Force anaconda openjdk

  run:
    - python
    - openjdk 8.0.152  # Force anaconda openjdk

test:
  imports:
    - jcc

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  files:
    - test/*.py
    - test/java-example/build_and_wrap.bat
    - test/java-example/build_and_wrap.sh
    - test/java-example/test1class.java

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
