{% set name = "JCC" %}
{% set version = "3.12" %}
{% set sha256 = "36a2ec9fa4f14ae33fb846ae231c7e054284eeedb84226f521acb5b7d0e23a0f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/fa/bf/c8ccdb84fb38986c9e1ec537e42db1d7c4d59491bcd30ae4798faadd3d9c/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    - jcc/config.py

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openjdk 8.*
    - pip

  host:
    - python
    - setuptools
    - openjdk 8.*
    - pip

  run:
    - python
    - openjdk 8.*

test:
  imports:
    - jcc  # [not win]

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  files:
    - test/*.py
    - test/java-example/*.bat
    - test/java-example/*.sh
    - test/java-example/*.java
    - test/java-example/*.py
    - test/java-example-test-parameters/*.bat
    - test/java-example-test-parameters/*.sh
    - test/java-example-test-parameters/org/jcc/test/*.java
    - test/java-example-test-parameters/*.py
    - test/java-example-shared/*.bat
    - test/java-example-shared/*.sh
    - test/java-example-shared/*.java
    - test/java-example-shared/*.py

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface  (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
