appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TArzfQ4Sx5Zt9Rl9vrqNcmojZ4JGL6cHUcKubl+hlvDkPgPldCHhZi2bcS+T5ap5JZCEORVfNAbcZq8vVAh1yd5ifWu7w2gESyh+Vc4vtoOtByu69nl03f4KNGqL8JlOz9C2ucbN4MIoKUzUgZBzdMC0WEMo3/NCZNtNEDs7nNPIagWAd/OWQbdyaA7gqsGl/Zry9phSPHtLMX3O+buEvcasi2+MmqC3lZK9tlSrq4SfVsxhEA+4pOZikOFd5FChrbyMYot7GQp0AX2L1YSkfz968vN8mMRUauI4q4ScBYwxSA1/+JhpkFLX8jcuuECeooADp+CD9pxriAws91shVKnnSnSpKraPkV1drEYQCcOnLn23rNER5zfjLMXZuZc8aug+fh0K4DR4MXimYJijSxfaNJFtTZAOTz63Bdv5ojZEZwpZWbYj7AWTfi1Xh7IwAM2bHOSf5iOZDtdS493GpGLS8E4WHKZGydLiKJEWPx/z1c+YWFkfVbKqIrySVh0BHHRsebr1TFzOmoeCn9cocThoDT0Lbbo3gfCrDQ4EfXN4Ay+rXHOpp/JXnWD18CZ7VpPc1cZu9GO/v+7L85r1426kgNJyBmiPrNDD4AQZ1mOWO8C2iIWPu7e+eIBc5CxqIzTl1lw63Oftm8GPXJSVAQbrRLWqRkuT5cyRfW02crM=}

channels:
  targets:
  - [conda-forge]
provider:
  win: azure
conda_forge_output_validation: true
