conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
azure:
  store_build_artifacts: True
  
build_platform:
  osx_arm64: osx_arm64
test: native
